name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Deploy with gh-pages
      run: |
        git config --global user.email "github-actions-bot@example.com"
        git config --global user.name "github-actions-bot"
        git remote set-url origin https://git:${secrets}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <github-actions-bot@example.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
